#==============================================================================
""" Creating Python code for use in Virtual NanoLab

    Code for modeling Indium crystal dynamics during melting
    
    Method of simulation used: NPTBerendsen, with
                                thermal coupling constant = 1000 fs
                                simulation steps = 10000

"""
#==============================================================================

# Setting up lattice structure of Indium Crystal

vector_a = [16.265, 0.0, 0.0]*Angstrom
vector_b = [0.0, 16.265, 0.0]*Angstrom
vector_c = [0.0, 0.0, 24.735]*Angstrom
lattice = UnitCell(vector_a, vector_b, vector_c)

# Defining composition of the lattice

elements = [Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium, Indium, Indium, Indium, Indium, Indium, Indium,
            Indium, Indium]

# Defining fractional  coordinates of the crystal lattice

fractional_coordinates = [[ 0.1,  0.1,  0.1],
                          [ 0.1,  0.1,  0.3],
                          [ 0.1,  0.1,  0.5],
                          [ 0.1,  0.1,  0.7],
                          [ 0.1,  0.1,  0.9],
                          [ 0.1,  0.3,  0.1],
                          [ 0.1,  0.3,  0.3],
                          [ 0.1,  0.3,  0.5],
                          [ 0.1,  0.3,  0.7],
                          [ 0.1,  0.3,  0.9],
                          [ 0.1,  0.5,  0.1],
                          [ 0.1,  0.5,  0.3],
                          [ 0.1,  0.5,  0.5],
                          [ 0.1,  0.5,  0.7],
                          [ 0.1,  0.5,  0.9],
                          [ 0.1,  0.7,  0.1],
                          [ 0.1,  0.7,  0.3],
                          [ 0.1,  0.7,  0.5],
                          [ 0.1,  0.7,  0.7],
                          [ 0.1,  0.7,  0.9],
                          [ 0.1,  0.9,  0.1],
                          [ 0.1,  0.9,  0.3],
                          [ 0.1,  0.9,  0.5],
                          [ 0.1,  0.9,  0.7],
                          [ 0.1,  0.9,  0.9],
                          [ 0.3,  0.1,  0.1],
                          [ 0.3,  0.1,  0.3],
                          [ 0.3,  0.1,  0.5],
                          [ 0.3,  0.1,  0.7],
                          [ 0.3,  0.1,  0.9],
                          [ 0.3,  0.3,  0.1],
                          [ 0.3,  0.3,  0.3],
                          [ 0.3,  0.3,  0.5],
                          [ 0.3,  0.3,  0.7],
                          [ 0.3,  0.3,  0.9],
                          [ 0.3,  0.5,  0.1],
                          [ 0.3,  0.5,  0.3],
                          [ 0.3,  0.5,  0.5],
                          [ 0.3,  0.5,  0.7],
                          [ 0.3,  0.5,  0.9],
                          [ 0.3,  0.7,  0.1],
                          [ 0.3,  0.7,  0.3],
                          [ 0.3,  0.7,  0.5],
                          [ 0.3,  0.7,  0.7],
                          [ 0.3,  0.7,  0.9],
                          [ 0.3,  0.9,  0.1],
                          [ 0.3,  0.9,  0.3],
                          [ 0.3,  0.9,  0.5],
                          [ 0.3,  0.9,  0.7],
                          [ 0.3,  0.9,  0.9],
                          [ 0.5,  0.1,  0.1],
                          [ 0.5,  0.1,  0.3],
                          [ 0.5,  0.1,  0.5],
                          [ 0.5,  0.1,  0.7],
                          [ 0.5,  0.1,  0.9],
                          [ 0.5,  0.3,  0.1],
                          [ 0.5,  0.3,  0.3],
                          [ 0.5,  0.3,  0.5],
                          [ 0.5,  0.3,  0.7],
                          [ 0.5,  0.3,  0.9],
                          [ 0.5,  0.5,  0.1],
                          [ 0.5,  0.5,  0.3],
                          [ 0.5,  0.5,  0.5],
                          [ 0.5,  0.5,  0.7],
                          [ 0.5,  0.5,  0.9],
                          [ 0.5,  0.7,  0.1],
                          [ 0.5,  0.7,  0.3],
                          [ 0.5,  0.7,  0.5],
                          [ 0.5,  0.7,  0.7],
                          [ 0.5,  0.7,  0.9],
                          [ 0.5,  0.9,  0.1],
                          [ 0.5,  0.9,  0.3],
                          [ 0.5,  0.9,  0.5],
                          [ 0.5,  0.9,  0.7],
                          [ 0.5,  0.9,  0.9],
                          [ 0.7,  0.1,  0.1],
                          [ 0.7,  0.1,  0.3],
                          [ 0.7,  0.1,  0.5],
                          [ 0.7,  0.1,  0.7],
                          [ 0.7,  0.1,  0.9],
                          [ 0.7,  0.3,  0.1],
                          [ 0.7,  0.3,  0.3],
                          [ 0.7,  0.3,  0.5],
                          [ 0.7,  0.3,  0.7],
                          [ 0.7,  0.3,  0.9],
                          [ 0.7,  0.5,  0.1],
                          [ 0.7,  0.5,  0.3],
                          [ 0.7,  0.5,  0.5],
                          [ 0.7,  0.5,  0.7],
                          [ 0.7,  0.5,  0.9],
                          [ 0.7,  0.7,  0.1],
                          [ 0.7,  0.7,  0.3],
                          [ 0.7,  0.7,  0.5],
                          [ 0.7,  0.7,  0.7],
                          [ 0.7,  0.7,  0.9],
                          [ 0.7,  0.9,  0.1],
                          [ 0.7,  0.9,  0.3],
                          [ 0.7,  0.9,  0.5],
                          [ 0.7,  0.9,  0.7],
                          [ 0.7,  0.9,  0.9],
                          [ 0.9,  0.1,  0.1],
                          [ 0.9,  0.1,  0.3],
                          [ 0.9,  0.1,  0.5],
                          [ 0.9,  0.1,  0.7],
                          [ 0.9,  0.1,  0.9],
                          [ 0.9,  0.3,  0.1],
                          [ 0.9,  0.3,  0.3],
                          [ 0.9,  0.3,  0.5],
                          [ 0.9,  0.3,  0.7],
                          [ 0.9,  0.3,  0.9],
                          [ 0.9,  0.5,  0.1],
                          [ 0.9,  0.5,  0.3],
                          [ 0.9,  0.5,  0.5],
                          [ 0.9,  0.5,  0.7],
                          [ 0.9,  0.5,  0.9],
                          [ 0.9,  0.7,  0.1],
                          [ 0.9,  0.7,  0.3],
                          [ 0.9,  0.7,  0.5],
                          [ 0.9,  0.7,  0.7],
                          [ 0.9,  0.7,  0.9],
                          [ 0.9,  0.9,  0.1],
                          [ 0.9,  0.9,  0.3],
                          [ 0.9,  0.9,  0.5],
                          [ 0.9,  0.9,  0.7],
                          [ 0.9,  0.9,  0.9],
                          [ 0. ,  0. ,  0. ],
                          [ 0. ,  0. ,  0.2],
                          [ 0. ,  0. ,  0.4],
                          [ 0. ,  0. ,  0.6],
                          [ 0. ,  0. ,  0.8],
                          [ 0. ,  0.2,  0. ],
                          [ 0. ,  0.2,  0.2],
                          [ 0. ,  0.2,  0.4],
                          [ 0. ,  0.2,  0.6],
                          [ 0. ,  0.2,  0.8],
                          [ 0. ,  0.4,  0. ],
                          [ 0. ,  0.4,  0.2],
                          [ 0. ,  0.4,  0.4],
                          [ 0. ,  0.4,  0.6],
                          [ 0. ,  0.4,  0.8],
                          [ 0. ,  0.6,  0. ],
                          [ 0. ,  0.6,  0.2],
                          [ 0. ,  0.6,  0.4],
                          [ 0. ,  0.6,  0.6],
                          [ 0. ,  0.6,  0.8],
                          [ 0. ,  0.8,  0. ],
                          [ 0. ,  0.8,  0.2],
                          [ 0. ,  0.8,  0.4],
                          [ 0. ,  0.8,  0.6],
                          [ 0. ,  0.8,  0.8],
                          [ 0.2,  0. ,  0. ],
                          [ 0.2,  0. ,  0.2],
                          [ 0.2,  0. ,  0.4],
                          [ 0.2,  0. ,  0.6],
                          [ 0.2,  0. ,  0.8],
                          [ 0.2,  0.2,  0. ],
                          [ 0.2,  0.2,  0.2],
                          [ 0.2,  0.2,  0.4],
                          [ 0.2,  0.2,  0.6],
                          [ 0.2,  0.2,  0.8],
                          [ 0.2,  0.4,  0. ],
                          [ 0.2,  0.4,  0.2],
                          [ 0.2,  0.4,  0.4],
                          [ 0.2,  0.4,  0.6],
                          [ 0.2,  0.4,  0.8],
                          [ 0.2,  0.6,  0. ],
                          [ 0.2,  0.6,  0.2],
                          [ 0.2,  0.6,  0.4],
                          [ 0.2,  0.6,  0.6],
                          [ 0.2,  0.6,  0.8],
                          [ 0.2,  0.8,  0. ],
                          [ 0.2,  0.8,  0.2],
                          [ 0.2,  0.8,  0.4],
                          [ 0.2,  0.8,  0.6],
                          [ 0.2,  0.8,  0.8],
                          [ 0.4,  0. ,  0. ],
                          [ 0.4,  0. ,  0.2],
                          [ 0.4,  0. ,  0.4],
                          [ 0.4,  0. ,  0.6],
                          [ 0.4,  0. ,  0.8],
                          [ 0.4,  0.2,  0. ],
                          [ 0.4,  0.2,  0.2],
                          [ 0.4,  0.2,  0.4],
                          [ 0.4,  0.2,  0.6],
                          [ 0.4,  0.2,  0.8],
                          [ 0.4,  0.4,  0. ],
                          [ 0.4,  0.4,  0.2],
                          [ 0.4,  0.4,  0.4],
                          [ 0.4,  0.4,  0.6],
                          [ 0.4,  0.4,  0.8],
                          [ 0.4,  0.6,  0. ],
                          [ 0.4,  0.6,  0.2],
                          [ 0.4,  0.6,  0.4],
                          [ 0.4,  0.6,  0.6],
                          [ 0.4,  0.6,  0.8],
                          [ 0.4,  0.8,  0. ],
                          [ 0.4,  0.8,  0.2],
                          [ 0.4,  0.8,  0.4],
                          [ 0.4,  0.8,  0.6],
                          [ 0.4,  0.8,  0.8],
                          [ 0.6,  0. ,  0. ],
                          [ 0.6,  0. ,  0.2],
                          [ 0.6,  0. ,  0.4],
                          [ 0.6,  0. ,  0.6],
                          [ 0.6,  0. ,  0.8],
                          [ 0.6,  0.2,  0. ],
                          [ 0.6,  0.2,  0.2],
                          [ 0.6,  0.2,  0.4],
                          [ 0.6,  0.2,  0.6],
                          [ 0.6,  0.2,  0.8],
                          [ 0.6,  0.4,  0. ],
                          [ 0.6,  0.4,  0.2],
                          [ 0.6,  0.4,  0.4],
                          [ 0.6,  0.4,  0.6],
                          [ 0.6,  0.4,  0.8],
                          [ 0.6,  0.6,  0. ],
                          [ 0.6,  0.6,  0.2],
                          [ 0.6,  0.6,  0.4],
                          [ 0.6,  0.6,  0.6],
                          [ 0.6,  0.6,  0.8],
                          [ 0.6,  0.8,  0. ],
                          [ 0.6,  0.8,  0.2],
                          [ 0.6,  0.8,  0.4],
                          [ 0.6,  0.8,  0.6],
                          [ 0.6,  0.8,  0.8],
                          [ 0.8,  0. ,  0. ],
                          [ 0.8,  0. ,  0.2],
                          [ 0.8,  0. ,  0.4],
                          [ 0.8,  0. ,  0.6],
                          [ 0.8,  0. ,  0.8],
                          [ 0.8,  0.2,  0. ],
                          [ 0.8,  0.2,  0.2],
                          [ 0.8,  0.2,  0.4],
                          [ 0.8,  0.2,  0.6],
                          [ 0.8,  0.2,  0.8],
                          [ 0.8,  0.4,  0. ],
                          [ 0.8,  0.4,  0.2],
                          [ 0.8,  0.4,  0.4],
                          [ 0.8,  0.4,  0.6],
                          [ 0.8,  0.4,  0.8],
                          [ 0.8,  0.6,  0. ],
                          [ 0.8,  0.6,  0.2],
                          [ 0.8,  0.6,  0.4],
                          [ 0.8,  0.6,  0.6],
                          [ 0.8,  0.6,  0.8],
                          [ 0.8,  0.8,  0. ],
                          [ 0.8,  0.8,  0.2],
                          [ 0.8,  0.8,  0.4],
                          [ 0.8,  0.8,  0.6],
                          [ 0.8,  0.8,  0.8]]

# Setting up bulk configuration

bulk_configuration = BulkConfiguration(
    bravais_lattice=lattice,
    elements=elements,
    fractional_coordinates=fractional_coordinates
    )

#==============================================================================
# Calculation
#==============================================================================

potentialSet = Tersoff_InAs_2008()
calculator = TremoloXCalculator(parameters=potentialSet)

bulk_configuration.setCalculator(calculator)
bulk_configuration.update()

#==============================================================================
# Molecular Dynamics
#==============================================================================

initial_velocity = MaxwellBoltzmannDistribution(
    temperature=0.0*Kelvin,
    remove_center_of_mass_momentum=True
)

method = NPTBerendsen(
    time_step=1*femtoSecond,
    reservoir_temperature=800*Kelvin,
    thermal_coupling_constant=1000*femtoSecond,
    reservoir_pressure=1*bar,
    pressure_coupling_constant=100*femtoSecond,
    compressibility=2.3e-06*bar**-1,
    initial_velocity=initial_velocity
)

md_trajectory = MolecularDynamics(
    bulk_configuration,
    constraints=[],
    trajectory_filename='trajectory.nc',
    steps=10000,
    log_interval=20,
    method=method
)

bulk_configuration = md_trajectory.lastImage()
nlsave('C:/Users/Dhinesh/Desktop/Research/Indium Melting New/Indium Melting New 1.nc', md_trajectory)